.shared_hidden_key: &shared 
  before_script:
    - docker login -u "<login>" -p "<password>"

stages:
 - build_images

 
job1:
  tags:
    - micro_runner
  <<: *shared
  stage: build_images
  script:
  - docker build -t <image-name> .
  - docker push <image-name>
